### ISSUE TITLE
Bot loses connection to gateway after a few hours

### ISSUE THREAD

**Issue by ghost** [Nixeld/MudaeAutoBot#1]
Does this version of the bot eventually lose access to the Discord Gateway and stops working like vivinano's version? The bot can't be ran overnight/endlessly, and has to be restarted manually. 

![image](https://github.com/Nixeld/MudaeAutoBot/assets/143224357/55ab2dec-f3a1-4a9c-bbca-f8638c2a7823)
Looks like this ^

**Comment by Nixeld** [comment]
![image](https://github.com/Nixeld/MudaeAutoBot/assets/18643932/c3817daa-b375-4746-8f3e-2a7075c6ce34)
I've been running it on a cloud platform for more than a month now on multiple accounts and I have never had it stop working. 
I think it might be a network related issue on your end. You can try to update discum to the latest version which is currently 1.4.1 if it is not already on that version.

**Comment by GuillermoDiazFentanes** [comment]
@Nixeld Hii !! what platform is that? id like to try it.
If you have some time, can you check a simple bot version I made? Im working on an advanced one to release it next year in several moths

https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023

**Comment by GuillermoDiazFentanes** [comment]
@magicalhobo2001 if you want to try my version feel free!

**Comment by ghost** [comment]
> I've been running it on a cloud platform for more than a month now on multiple accounts and I have never had it stop working. I think it might be a network related issue on your end. You can try to update discum to the latest version which is currently 1.4.1 if it is not already on that version.

I already have discum updated. Do you have any other potential solutions?

**Comment by GuilleDiazFentanes** [comment]
@magicalhobo2001 you can try my other solution until u fix the other one! its very simple only 3 files and no need to input more than token guild/channel id

**Comment by Nixeld** [comment]
> @Nixeld Hii !! what platform is that? id like to try it. If you have some time, can you check a simple bot version I made? Im working on an advanced one to release it next year in several moths
> 
> https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2023

I am using Zeabur running the script in a docker container. You get $5 credit free per month which is enough for about 7 or 8 accounts.

**Comment by HANSSS9631** [comment]
![image_2023-12-24_143138095](https://github.com/Nixeld/MudaeAutoBot/assets/97141634/0cd25989-4eda-4881-8eee-49909d77f1f1)
I see what you where talking about and found that it was some issue with `discum` and it randomly restarted itself after a long time. Then rolls but does not receive any msg from the channel and stops rolling because it thinks mudae is down. Then disconnects again because it does not receive any msg from the channel.
There is no way to fix it unless we switch `discum` to `discord.py-self` to test that one instead @Nixeld

**Comment by Nixeld** [comment]
There seems to be a problem with Discum's auto reconnect feature. A workaround for this issue is to disable auto reconnect and restart the script using other methods.

An AutoReconnect.py has been added to start and automatically restart MudaeAutoBot whenever it disconnects. 
Please run the bot with AutoReconnect.py from now onwards.

Thanks @HentaiRyuu for the workaround.
