### ISSUE TITLE
[Bug] Bot only claims characters on the namelist, in spite of the minimum kakera

### ISSUE THREAD

**Issue by ghost** [Nixeld/MudaeAutoBot#15]
I've done a lot of testing, and I've discovered that the bot only reliably claims characters specified in `"namelist"` of `Settings_Mudae.json`

If it's not on the namelist, it the bot will usually not register that the character even spawned.

**Comment by Nixeld** [comment]
Could you share your Settings_Mudae.json without your token.

**Comment by ghost** [comment]
![image](https://github.com/Nixeld/MudaeAutoBot/assets/167378686/9785c9ae-5803-4b7a-adad-0e5c17ceb4ea)
I also excluded channel and server ids

**Comment by Nixeld** [comment]
So from what I understand, the problem is the bot not claiming any characters that are above 500 kakera? 
Based on your current settings, the bot will **only claim characters that are worth 500 or more kakera**.

Have you also made sure that the bot has not already claimed a character within that claim window?

If there are any characters in the name or series list, the bot will ignore the minimum kakera value and claim those characters in the list. So if the problem is not being able to claim any characters until unless specified in the name list, then it is possibly a problem with your minimum kakera value set.

**Comment by ghost** [comment]
Maybe it's just me. I'll close the issue for now unless something else comes up.
